package unprg.capa_presentacion;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import unprg.capa_datos.MaterialDAO;
import unprg.capa_logica.modelos.Material;
import unprg.capa_presentacion.utils.UiHelper;

/**
 *
 * @author mauricio
 */
public class JdAgregarMaterial extends javax.swing.JDialog {

    MaterialDAO materialDAO = new MaterialDAO();
    private String material = "";
    private int cant = 0;
    private int desc = 0;

    /**
     * Creates new form jdAgregarPedido
     */
    public JdAgregarMaterial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarEstilos();
        listado();
        configurarFiltro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListado = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Ingrese nombre del producto");

        tblListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListado);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarEstilos() {
        UiHelper.estilarCampoForm(txtBuscar, "Buscar material...");
    }

    private void pasarDatos(String producto, int ctd) {
        try {
            Material m = materialDAO.getElemento(producto);
            
            if (m != null) {
                int stock = m.getStock();
                
                if (ctd <= stock) {
                    material = producto;
                    cant = ctd;
                    
                    String descuento = JOptionPane.showInputDialog(rootPane, "Ingrese el porcentaje", "0");
                    
                    if (descuento != null) {
                        try {
                            desc = Integer.parseInt(descuento);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(rootPane, "El descuendo debe ser un numero valido");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Stock insuficiente. Disponible " + stock);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Material no encontrado en la lista");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: " + e.getMessage());
        }
    }
    
    private void tblListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListadoMouseClicked
        if (evt.getClickCount() == 1) {
            int filaSeleccionada = tblListado.getSelectedRow();
            if (filaSeleccionada != -1) {
                String producto = String.valueOf(tblListado.getValueAt(filaSeleccionada, 0));
                
                String ctd = JOptionPane.showInputDialog(rootPane, "Ingrese la cantidad: ", "1");
                
                if (ctd != null && !ctd.trim().isEmpty()) {
                    try {
                        int cantidad = Integer.parseInt(ctd);
                        if (cantidad > 0) {
                            pasarDatos(producto, cantidad);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "La cantidad debe ser mayor a 0");
                        }
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(rootPane, "Cantidad no válida");
                    }
                }
            }
        }
    }//GEN-LAST:event_tblListadoMouseClicked

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        listado();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void configurarFiltro() {
        txtBuscar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrar();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrar();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrar();
            }
        });
    }

    private void filtrar() {
        String textoBusqueda = txtBuscar.getText().trim().toLowerCase();

        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modelo.addColumn("Materiales");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        modelo.addColumn("Tipo medida");

        List<Material> materiales = new MaterialDAO().listar();

        if (materiales != null) {
            for (Material m : materiales) {
                if (textoBusqueda.isEmpty()
                    || m.getNombProducto().toLowerCase().contains(textoBusqueda)) {
                    modelo.addRow(new Object[]{
                        m.getNombProducto(),
                        m.getDescripcion(),
                        m.getPrecioUnitario(),
                        m.getStock(),
                        m.getUnidadMedida()
                    });
                }
            }
        }
        tblListado.setModel(modelo);
    }

    private void listado() {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modelo.addColumn("Material");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        modelo.addColumn("Tipo de medida");

        List<Material> materiales = new MaterialDAO().listar();

        if (materiales != null) {
            for (Material m : materiales) {
                
                modelo.addRow(new Object[]{
                    m.getNombProducto(),
                    m.getDescripcion(),
                    m.getPrecioUnitario(),
                    m.getStock(),
                    m.getUnidadMedida()
                });
            }
        }
        tblListado.setModel(modelo);
    }

    public String getMaterial() {
        return material;
    }

    public void setMaterial(String material) {
        this.material = material;
    }

    public int getCant() {
        return cant;
    }

    public void setCant(int cant) {
        this.cant = cant;
    }

    public int getDescuento() {
        return desc;
    }

    public void setDescuento(int descuento) {
        this.desc = descuento;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListado;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
